### ISSUE TITLE
Update process is broken

### ISSUE THREAD

**Issue by bernd-wechner** [hi-ko/joplin-server-ubuntu-install#8]
This will need a little tweaking. No time right now so just making a note.  

I noticed that [server-v2.7.4](https://github.com/laurent22/joplin/releases/tag/server-v2.7.4) is available and heck I'm always kinda keen to have the latest ;-).

So I followed the README update process. Two problems emerged:

1. The first `cd` misses a level. The requirements script checked it out to `~/joplin/joplin` so we need to `cd` there to run git commands. (small issue, easily fixed)
2. Attempting bails with dependency errors. Looks like the new version demands newer versions too of things it depends on but somehow they aren't fetched or updated. I'm a bit green with node (as in this is my first sally with it) so can't fix it in a minute, will need a little thinking, reading, learning, experimenting. If, of course someone else wants to try it and knows node better and can fix this with one line, please do.

The good news is I could wind back server-v2.6.14 and rebuild  and nothing is broken.  All is good. 

The bad news is, I'd like to upgrade to server-v2.7.4 and can't (don't know how) yet.

**Comment by hi-ko** [comment]
latest joplin version made major changes in the dockerfile and switched from npm to yarn for the basic server build, so the install script needs to adapt all these latest changes. s. #7 
I created a new feature request to separate server build (we are interested in only) from the docker image build (Dockerfile): https://discourse.joplinapp.org/t/feature-request-separate-joplin-server-from-dockerfile-build/23470 to avoid that permanent rework on every joplin version

**Comment by rokdd** [comment]
All the time this changes.. I would also say that the scripts should use an installation folder like /etc/joplin to avoid this path / user / .joplinrc problems.

**Comment by bernd-wechner** [comment]
Lets get it so we can all update to latest then ... Who's gonna work on it? ;-) We might be able to semi automate the build file using something like:

https://github.com/thatkevin/dockerfile-to-shell-script

Always with caveat emptor in place ... that is, the conversion should always be inspected before run.

**Comment by hi-ko** [comment]
It's still a work in progress but you may take a look into the branch [rework_build_yarn](/hi-ko/joplin-server-ubuntu-install/tree/rework_build_yarn)
````
Usage: ./joplin.sh {checkout-latest|build|install|makeall|run}
````
open:
* support all variables from /default in joplin.sh
* documentation
* install may also create all required files and dirs
* source bash functions from lib

**Comment by bsod-haunted** [comment]
> It's still a work in progress but you may take a look into the branch [rework_build_yarn](/hi-ko/joplin-server-ubuntu-install/tree/rework_build_yarn)
> 
> ```
> Usage: ./joplin.sh {checkout-latest|build|install|makeall|run}
> ```

Hi, thanks for the greate work on the scipt!
I created two pull requests with changes i found trying to get Server 2.7.4 to run
#12 
#11 

Not sure if this is the right place to ask this.
Joplin Server 2.7.4 cannot connect to the postgres db after setting it up.

what i did was:
I copyed the defaults file to /etc/default and changed the values as needed.
installed Postgres and created the DB as discribed in [README.md](https://github.com/hi-ko/joplin-server-ubuntu-install/blob/rework_build_yarn/README.md) + enabled connections on localhost
Then I used the scripts in the rework_build_yarn branch, ([install-requirements.sh](https://github.com/hi-ko/joplin-server-ubuntu-install/blob/rework_build_yarn/install-requirements.sh) and [joplin.sh](https://github.com/hi-ko/joplin-server-ubuntu-install/blob/rework_build_yarn/joplin.sh)

However, trying to run the Joplin server creates the following error:
```
2022-05-03 09:20:20: App: Content driver: { type: 1 }
2022-05-03 09:20:20: App: Content driver (fallback): null
2022-05-03 09:20:20: App: Trying to connect to database...
2022-05-03 09:20:50: db: Could not connect. Will try again. Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
2022-05-03 09:20:50: [error] db: Timeout trying to connect to database: KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_PG.acquireConnection (/opt/joplin/packages/server/node_modules/knex/lib/client.js:295:26)
    at Runner.ensureConnection (/opt/joplin/packages/server/node_modules/knex/lib/execution/runner.js:259:28)
    at Runner.run (/opt/joplin/packages/server/node_modules/knex/lib/execution/runner.js:30:19) {
  sql: undefined,
  bindings: undefined
}
```

I was not able to find a solution via google, but I am a newbee to postgres, NPM and Yarn...

Is there a resource availabe that i can use to figure out why this happens?

**Comment by hi-ko** [comment]
Hi @bsod-haunted,
thanks a lot for you pull requests. I commented there.

postgres: the database is running on the same server? could you try to connect to the database using `psql` and your credentials used in the config?

**Comment by bsod-haunted** [comment]
Hi @hi-ko, thanks for your reply.
The error was me beeing stupid.
I managed to get a typo in the localhost ip...
Wich i realized because `psql -h localhost` worked.

Sorry for wasting your time. Thanks again for your awesom scripts!

**Comment by hi-ko** [comment]
no problem @bsod-haunted. Thanks for the prompt feedback.

**Comment by bernd-wechner** [comment]
> It's still a work in progress but you may take a look into the branch [rework_build_yarn](/hi-ko/joplin-server-ubuntu-install/tree/rework_build_yarn)
> 
> ```
> Usage: ./joplin.sh {checkout-latest|build|install|makeall|run}
> ```
> 
> open:
> 
>     * support all variables from /default in joplin.sh
> 
>     * documentation
> 
>     * install may also create all required files and dirs
> 
>     * source bash functions from lib

Just a random check-in on this. Any time to work on it? I clearly haven't alas.

**Comment by hi-ko** [comment]
Hi @bernd-wechner thanks for your work!
I put the open point to my holiday todo list in August ;-)
